# Generated by Django 5.2.1 on 2025-07-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Hero title', max_length=150, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=150)),
                ('product_category', models.CharField(max_length=100)),
                ('key_benifits', models.CharField(max_length=150)),
                ('target_audience', models.CharField(max_length=150)),
                ('scripts_ton', models.CharField(max_length=100)),
                ('script_title', models.CharField(max_length=150)),
                ('script', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
                'ordering': ['script_title'],
            },
        ),
    ]
