# Generated by Django 5.2.1 on 2025-07-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_script_script_alter_script_script_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('discount_price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regular_price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_price_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regular_price_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('have_access_scripts_per_month', models.BooleanField(default=True)),
                ('access_scripts_per_month', models.IntegerField(default=0)),
                ('full_scripts_library_access', models.BooleanField(default=True)),
                ('downloadable_template', models.BooleanField(default=False)),
                ('ai_screept_generator', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['title'],
            },
        ),
    ]
