# Generated by Django 5.2.1 on 2025-07-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_package_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='stripe_monthly_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='stripe_yearly_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
