# Generated by Django 5.2.1 on 2025-07-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_coach',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_player',
        ),
    ]
